CREATE SCHEMA IF NOT EXISTS darwin;
SET search_path TO darwin, public;

-- messagexml

CREATE TABLE IF NOT EXISTS darwin.message_xml ( 
				rdm_id text PRIMARY KEY 

				,kafka_offset bigint NOT NULL
				,xml xml NOT NULL
);

-- pport

CREATE TABLE IF NOT EXISTS darwin.messages (
				rdm_id text PRIMARY KEY
				,CONSTRAINT fk_message_xml FOREIGN KEY(rdm_id) REFERENCES message_xml(rdm_id) ON DELETE CASCADE

				,version text NOT NULL -- version of Darwin Push Port that the message was generated by
				,sent_at timestamp WITH TIME ZONE NOT NULL -- The time that Darwin Push Port sent this message.
				,first_received_at timestamp WITH TIME ZONE NOT NULL -- The first time that railreader recieved this message.
				,last_received_at timestamp WITH TIME ZONE NOT NULL -- The most recent time that railreader has recieved this message.

				-- If a status element is given:
				,status_code varchar(32) NULL -- The status of the message feed's connection to Darwin: HBOK, HBINIT, HBFAIL, HBPENDING
				,status_description varchar(128) NULL -- Human-readable description of the status code.

				-- If a response element is given:
				,response_is_snapshot boolean NULL -- If false, the response is an 'update'. 
				,request_source text NULL
				,request_source_system char(4) NULL
				,request_id varchar(16) NULL
);

-- Reference data

CREATE TABLE IF NOT EXISTS darwin.references ( -- Reference data files that have been imported
				id char(14) PRIMARY KEY
				,filename varchar(128) NOT NULL
				,imported_at timestamp WITH TIME ZONE NOT NULL
				,message_id text NULL -- set if the reference data import was triggered by a Darwin message
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS darwin.locations ( -- TIming Point LOCcations
				id varchar(7) PRIMARY KEY 
				,crs_id char(3) NULL
				,toc_id char(2) NULL -- No foreign key constraint is used here because not all possible toc_ids are included in the reference data set.
				,name varchar(30) NULL
);

CREATE TABLE IF NOT EXISTS darwin.user_location_overrides ( -- User-defined overrides for location names
				location_id varchar(7) PRIMARY KEY
				,name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.tocs ( -- Train Operating Companies
				id char(2) PRIMARY KEY
				,name varchar(256) NOT NULL
				,url varchar(512) NULL
);

CREATE TABLE IF NOT EXISTS darwin.late_reasons ( -- Reasons why a train service is running late.
				id int PRIMARY KEY 
				,description varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.cancellation_reasons ( -- Reasons why a train service is cancelled.
				id int PRIMARY KEY
				,description varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.via_conditions ( -- A set of conditions that must be met for a 'via' message to be displayed for a service.
				id uuid PRIMARY KEY

				,sequence int -- Sequence number is important here, as only the lowest-numbered (first) matching via condition should be displayed.

				,display_at_crs_id char(3) NOT NULL 
				,first_required_location_id varchar(7) NOT NULL
				,second_required_location_id varchar(7) NULL
				,destination_required_location_id varchar(7) NOT NULL 
				,text varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.cis ( -- Customer Information Systems 
				id char(4) PRIMARY KEY
				,name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.loading_categories ( -- Categories that can be used to represent a rough estimate on how full a train is
				id uuid PRIMARY KEY -- Generated by railreader (not given by Darwin)

				,code varchar(4) NOT NULL
				,toc_id char(2) NULL
				,CONSTRAINT uq_code_toc UNIQUE NULLS NOT DISTINCT (code, toc_id)
				-- Default values for each code are specified here as records where toc_id is NULL.
				-- TOCs give an override for the default values of a code using a seperate record with the same code, but containing their toc_id.

				,name varchar(16) NOT NULL 
				,description_typical varchar(200) NOT NULL
				,description_expected	varchar(200) NOT NULL
				,definition varchar(1000) NOT NULL
);

-- timetable

CREATE TABLE IF NOT EXISTS darwin.timetables ( -- Timetable files that have been imported
				id char(14) PRIMARY KEY
				,filename varchar(128) NOT NULL
				,imported_at timestamp WITH TIME ZONE NOT NULL
				,message_id text NULL -- set if the timetable import was triggered by a Darwin message
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
);

-- alarm

CREATE TABLE IF NOT EXISTS darwin.alarms ( -- Alarms raised when Darwin has not recieved data from some of its sources.
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

		  	,alarm_id int 
				,has_cleared boolean NOT NULL

				-- if has_cleared is false:
				,train_describer_failure char(2) NULL -- a specific train describer that is suspected to have failed
				,all_train_describers_failed boolean NULL
				,tyrell_failed boolean NULL
);

-- association

CREATE TABLE IF NOT EXISTS darwin.associations ( -- Links between two schedules
				id uuid PRIMARY KEY

				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
				,timetable_id char(14) NULL
				,CONSTRAINT fk_timetable FOREIGN KEY(timetable_id) REFERENCES timetables(id) ON DELETE CASCADE

				,location_id varchar(7) NOT NULL
				,category char(2) NOT NULL -- "JJ", "VV", "LK", "NP"
				,is_cancelled boolean NOT NULL -- won't happen
				,is_deleted boolean NOT NULL -- doesn't exist, possibly invalid

				,main_schedule_id char(16) NOT NULL
				,main_schedule_working_arrival_time varchar(8) NULL
				,main_schedule_working_passing_time varchar(8) NULL
				,main_schedule_working_departure_time varchar(8) NULL
				,main_schedule_public_arrival_time char(5) NULL
				,main_schedule_public_departure_time char(5) NULL

				,associated_schedule_id char(16) NOT NULL
				,associated_schedule_working_arrival_time varchar(8) NULL
				,associated_schedule_working_passing_time varchar(8) NULL
				,associated_schedule_working_departure_time varchar(8) NULL
				,associated_schedule_public_arrival_time char(5) NULL
				,associated_schedule_public_departure_time char(5) NULL
);

-- deactivation

CREATE TABLE IF NOT EXISTS darwin.deactivations (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				schedule_id char(16)
);

-- forecast

CREATE TABLE IF NOT EXISTS darwin.schedule_forecasts (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL

				,is_reverse_formation boolean NOT NULL

				,late_reason_id int NULL
				,late_reason_location_id varchar(7) NULL
				,late_reason_is_near_location boolean NULL
);

CREATE TABLE IF NOT EXISTS darwin.schedule_location_forecasts (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL
				,location_id varchar(7) NOT NULL
				,schedule_working_arrival_time varchar(8) NULL
				,schedule_working_passing_time varchar(8) NULL
				,schedule_working_departure_time varchar(8) NULL
				,schedule_public_arrival_time char(5) NULL
				,schedule_public_departure_time char(5) NULL

				,arrival_estimated_time char(5) NULL -- HH:MM
				,arrival_estimated_working_time char(5) NULL
				,arrival_minimum_estimated_time char(5) NULL
				,arrival_estimated_time_is_unknown boolean NULL
				,arrival_is_delayed boolean NULL
				,arrival_actual_time char(5) NULL
				,arrival_actual_time_class text NULL
				,arrival_data_source text NULL
				,arrival_data_source_system char(4) NULL
				
				,passing_estimated_time char(5) NULL -- HH:MM
				,passing_estimated_working_time char(5) NULL
				,passing_minimum_estimated_time char(5) NULL
				,passing_estimated_time_is_unknown boolean NULL
				,passing_is_delayed boolean NULL
				,passing_actual_time char(5) NULL
				,passing_actual_time_class text NULL
				,passing_data_source text NULL
				,passing_data_source_system char(4) NULL

				,departure_estimated_time char(5) NULL -- HH:MM
				,departure_estimated_working_time char(5) NULL
				,departure_minimum_estimated_time char(5) NULL
				,departure_estimated_time_is_unknown boolean NULL
				,departure_is_delayed boolean NULL
				,departure_actual_time char(5) NULL
				,departure_actual_time_class text NULL
				,departure_data_source text NULL
				,departure_data_source_system char(4) NULL

				,late_reason_id int NULL
				,late_reason_location_id varchar(7) NULL
				,late_reason_is_near_location boolean NULL
				
				,disruption_risk text NULL -- "Delay", "Cancellation", or "Other".
				,disruption_risk_reason_id int NULL
				,disruption_risk_reason_location_id text NULL
				,disruption_risk_reason_is_near_location boolean NULL

				,affected_by varchar(16) NULL
 				,length int NULL -- may or may not match formation data

				,platform_is_supressed boolean NULL
				,platform_is_supressed_by_cis boolean NULL
				,platform_data_source char NULL -- "P", "A", "M"
				,platform_is_confirmed boolean NULL
				,platform varchar(3) NULL -- also set by Journey data in timetables

				,is_suppressed boolean NOT NULL
				,detaches_from_front boolean NOT NULL
);

-- formation

CREATE TABLE IF NOT EXISTS darwin.formations (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL
				,formation_id varchar(20) NOT NULL
				,source text NULL
				,source_system char(4) NULL
);

CREATE TABLE IF NOT EXISTS darwin.formation_coach (
				id uuid PRIMARY KEY

				,formation_uuid uuid NOT NULL
				,CONSTRAINT fk_formation_uuid FOREIGN KEY(formation_uuid) REFERENCES formaitions(id) ON DELETE CASCADE

				,formation_id varchar(20) NOT NULL
				,identifier varchar(2) NOT NULL
				,class text NULL
				,toilet_type text NULL
				,toilet_status text NULL
);

-- formationloading

CREATE TABLE IF NOT EXISTS darwin.formation_loading (
				id uuid PRIMARY KEY

				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL
				,formation_id varchar(20) NOT NULL
				,location_id varchar(7) NOT NULL
				,schedule_working_arrival_time varchar(8) NULL
				,schedule_working_passing_time varchar(8) NULL
				,schedule_working_departure_time varchar(8) NULL
				,schedule_public_arrival_time char(5) NULL
				,schedule_public_departure_time char(5) NULL
				
				,identifier varchar(2) NOT NULL
				,source text NULL
				,source_system char(4) NULL
				,percentage int NOT NULL
);

-- headcodechange

CREATE TABLE IF NOT EXISTS darwin.headcode_change (
				id uuid PRIMARY KEY

				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,old_headcode char(4) NOT NULL
				,new_headcode char(4) NOT NULL

				,train_describer char(2) NOT NULL
				,train_describer_berth char(4) NOT NULL
);

-- schedule

CREATE TABLE IF NOT EXISTS darwin.schedules ( -- Schedule for a specific train service
				id uuid PRIMARY KEY

				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
				,timetable_id char(14) NULL
				,CONSTRAINT fk_timetable FOREIGN KEY(timetable_id) REFERENCES timetables(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL -- the RID
				,uid char(6) NOT NULL
				,scheduled_start_date char(10) NOT NULL -- YYYY-MM-DD

				,headcode char(4) NOT NULL
				,retail_service_id varchar(8) NULL
				,toc_id char(2) NOT NULL 
				-- No foreign key constraint is used here because not all possible toc_ids are included in the reference data set.
				,service char NOT NULL
				,category varchar(2) NOT NULL
				,is_passenger_service boolean NOT NULL
				,is_active boolean NOT NULL
				,is_deleted boolean NOT NULL
				,is_charter boolean NOT NULL

				,cancellation_reason_id int NULL
				,cancellation_reason_location_id varchar(7) NULL
				,cancellation_reason_is_near_location boolean NULL

				,diverted_via_location_id varchar(7) NULL

				,diversion_reason_id int NULL
				,diversion_reason_location_id varchar(7) NULL
				,diversion_reason_is_near_location boolean NULL

				-- only in Journey
				,is_cancelled boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.schedule_locations ( -- Locations that a schedule visits
				id uuid PRIMARY KEY

				,schedule_uuid uuid NOT NULL
				,CONSTRAINT fk_schedule_uuid FOREIGN KEY(schedule_uuid) REFERENCES schedules(id) ON DELETE CASCADE
				,schedule_id char(16) NOT NULL

				-- Schedule
				,location_id varchar(7) NOT NULL
				,activities char(2) ARRAY NULL
				,planned_activities char(2) ARRAY NULL
				,is_cancelled boolean NOT NULL
				,formation_id varchar(20) NULL
				,is_affected_by_diversion boolean NOT NULL

				,type text NOT NULL
				-- Times are given here as text so that they can be serached through in their original format. They can be converted to timestamps as needed.

				,working_arrival_time	varchar(8) NULL -- HH:MM[:SS]
				,working_passing_time varchar(8) NULL
				,working_departure_time varchar(8) NULL
				,public_arrival_time char(5) NULL -- HH:MM
				,public_departure_time char(5) NULL
				,routing_delay int NOT NULL -- in minutes
				,false_destination_location_id varchar(7) NULL

				,cancellation_reason_id int NULL
				,cancellation_reason_location_id varchar(7) NULL
				,cancellation_reason_is_near_location boolean NULL
);

-- serviceloading

CREATE TABLE IF NOT EXISTS darwin.service_loadings (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL
				,location_id varchar(7) NOT NULL
				,schedule_working_arrival_time varchar(8) NULL
				,schedule_working_passing_time varchar(8) NULL
				,schedule_working_departure_time varchar(8) NULL
				,schedule_public_arrival_time char(5) NULL
				,schedule_public_departure_time char(5) NULL

				,loading_category_code varchar(4) NULL
				,loading_category_source text NULL
				,loading_category_source_system char(4) NULL
				,loading_category_type text NULL -- "Typical", "Expected"

				,loading_percentage int NULL
				,loading_percentage_source text NULL
				,loading_percentage_source_system char(4) NULL
				,loading_percentage_type text NULL -- "Typical", "Expected"
);

-- stationmessage

CREATE TABLE IF NOT EXISTS darwin.station_messages (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,station_message_id int NOT NULL
				,category text NOT NULL -- "Train", "Station", "Connections", "System", "Misc", "PriorTrains", "PriorOther"
				,severity int NOT NULL -- 0 (normal), 1 (minor), 2 (major), 3 (severe)
				,is_suppressed boolean NOT NULL

				,station_crs_codes char(3) ARRAY NOT NULL
				,body xml NOT NULL
);

-- trainalert

CREATE TABLE IF NOT EXISTS darwin.train_alerts (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,alert_id varchar(16) NOT NULL
				,copied_from_alert_id varchar(16) NULL
				,should_send_sms boolean NOT NULL
				,should_send_email boolean NOT NULL
				,should_send_tweet boolean NOT NULL
				,source text NOT NULL
				,copied_from_source text NULL
				,audience text NOT NULL -- "Customer", "Staff", "Operations"
				,type text NOT NULL -- "Normal", "Forced"

				,body xml NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.train_alert_schedule_locations (
				id uuid PRIMARY KEY

				,train_alert_id uuid NOT NULL
				,CONSTRAINT fk_train_alert FOREIGN KEY(train_alert_id) REFERENCES train_alerts(id) ON DELETE CASCADE

				,schedule_id char(16) NOT NULL
				,location_ids varchar(7) ARRAY NOT NULL
);

-- trainorder

CREATE TABLE IF NOT EXISTS darwin.train_orders (
				id uuid PRIMARY KEY

				,message_id text NOT NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,location_id varchar(7) NOT NULL
				,platform varchar(3) NOT NULL

				,clear_order boolean NOT NULL

				,first_service_rid char(16) NOT NULL
				,first_service_headcode char(4) NOT NULL
				,first_service_working_arrival_time varchar(8) NULL
				,first_service_working_passing_time varchar(8) NULL
				,first_service_working_departure_time varchar(8) NULL
				,first_service_public_arrival_time char(5) NULL
				,first_service_public_departure_time char(5) NULL

				,second_service_rid char(16) NOT NULL
				,second_service_headcode char(4) NOT NULL
				,second_service_working_arrival_time varchar(8) NULL
				,second_service_working_passing_time varchar(8) NULL
				,second_service_working_departure_time varchar(8) NULL
				,second_service_public_arrival_time char(5) NULL
				,second_service_public_departure_time char(5)  NULL

				,third_service_rid char(16) NULL
				,third_service_headcode char(4)  NULL
				,third_service_working_arrival_time varchar(8) NULL
				,third_service_working_passing_time varchar(8) NULL
				,third_service_working_departure_time varchar(8) NULL
				,third_service_public_arrival_time char(5) NULL
				,third_service_public_departure_time char(5) NULL
);
