CREATE SCHEMA IF NOT EXISTS darwin;
SET search_path TO darwin, public;

-- Reference data

CREATE TABLE IF NOT EXISTS darwin.references ( -- Reference data files that have been imported
				filename text PRIMARY KEY
				,imported_at timestamp WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.locations ( -- TIming Point LOCcations
				id varchar(7) PRIMARY KEY 
				,crs_id char(3) NULL
				,toc_id char(2) NULL -- No foreign key constraint is used here because not all possible toc_ids are included in the reference data set.
				,name varchar(30) NULL
);

CREATE TABLE IF NOT EXISTS darwin.tocs ( -- Train Operating Companies
				id char(2) PRIMARY KEY
				,name varchar(256) NOT NULL
				,url varchar(512) NULL
);

-- late_reason IDs and cancellation_reason IDs overlap, so it is important to distinguish between them.

CREATE TABLE IF NOT EXISTS darwin.late_reasons ( -- Reasons why a train service is running late.
				id int PRIMARY KEY 
				,description varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.cancellation_reasons ( -- Reasons why a train service is cancelled.
				id int PRIMARY KEY
				,description varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.via_conditions ( -- A set of conditions that must be met for a 'via' message to be displayed for a service.
				sequence int PRIMARY KEY -- Sequence number is important here, as only the lowest-numbered (first) matching via condition should be displayed.
				,display_at_crs_id char(3) NOT NULL 
				,first_required_location_id varchar(7) NOT NULL
				,CONSTRAINT fk_first_required_location FOREIGN KEY(first_required_location_id) REFERENCES locations(id) ON DELETE CASCADE
				,second_required_location_id varchar(7) NULL
				,CONSTRAINT fk_second_required_location FOREIGN KEY(second_required_location_id) REFERENCES locations(id) ON DELETE CASCADE
				,destination_required_location_id varchar(7) NOT NULL 
				,CONSTRAINT fk_destination_required_location FOREIGN KEY(destination_required_location_id) REFERENCES locations(id) ON DELETE CASCADE
				,text varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.cis ( -- Customer Information Systems 
				id char(4) PRIMARY KEY 
				,name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS darwin.loading_categories ( -- Categories that can be used to represent a rough estimate on how full a train is
				id uuid PRIMARY KEY -- Generated by railreader (not given by Darwin)

				,code varchar(4) NOT NULL
				,toc_id char(2) NULL
				,CONSTRAINT uq_code_toc UNIQUE NULLS NOT DISTINCT (code, toc_id)
				-- Default values for each code are specified here as records where toc_id is NULL.
				-- TOCs give an override for the default values of a code using a seperate record with the same code, but containing their toc_id.

				,name varchar(16) NOT NULL 
				,description_typical varchar(200) NOT NULL
				,description_expected	varchar(200) NOT NULL
				,definition varchar(1000) NOT NULL
);

-- messagexml

CREATE TABLE IF NOT EXISTS darwin.message_xml ( -- Raw XML messages stored to use for debugging.
				id text PRIMARY KEY -- id as given by the Rail Data Marketplace
				,xml xml NOT NULL
				,kafka_offset bigint NOT NULL
);

-- pport

CREATE TABLE IF NOT EXISTS darwin.messages ( -- Successfully processed messages.
				id text PRIMARY KEY -- id as given by the Rail Data Marketplace
				,CONSTRAINT fk_message_xml FOREIGN KEY(id) REFERENCES message_xml(id) ON DELETE CASCADE
				,version text NOT NULL -- version of Darwin the message was generated by
				,sent_at timestamp WITH TIME ZONE NOT NULL
				,first_received_at timestamp WITH TIME ZONE NOT NULL -- The most recent time that railreader has recieved this message.

				-- If a status element is given:
				,status_code varchar(32) NULL -- The status of the message feed's connection to Darwin.
				,status_description varchar(128) NULL -- Human-readable description of the status code.

				-- If a response element is given:
				,response_is_snapshot boolean NULL -- If false, the response is an 'update'. 
				,request_source text NULL
				,request_source_system char(4) NULL
				,request_id varchar(16) NULL
);

-- timetable

CREATE TABLE IF NOT EXISTS darwin.timetables ( -- Timetable files that have been imported
				id char(14) PRIMARY KEY
				,filename varchar(128) NOT NULL
				,imported_at timestamp WITH TIME ZONE NOT NULL
);

-- schedule

CREATE TABLE IF NOT EXISTS darwin.schedules ( -- Schedule for a specific train service
				id char(16) PRIMARY KEY -- this is the RID, renamed to be consistent with other tables

				-- sources
				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
				,timetable_id char(14) NULL
				,CONSTRAINT fk_timetable FOREIGN KEY(timetable_id) REFERENCES timetables(id) ON DELETE CASCADE

				-- TrainIdentifiers
				,uid char(6) NOT NULL
				,scheduled_start_date date NOT NULL

				-- Schedule
				,headcode char(4) NOT NULL
				,retail_service_id varchar(8) NULL
				,toc_id char(2) NOT NULL -- no foreign key contraint here, reference data on TOCs is not complete
				-- No foreign key constraint is used here because not all possible toc_ids are included in the reference data set.
				,service char NOT NULL
				,category varchar(2) NOT NULL
				,is_passenger_service boolean NOT NULL
				,is_active boolean NOT NULL
				,is_deleted boolean NOT NULL
				,is_charter boolean NOT NULL

				,cancellation_reason_id int NULL
				,CONSTRAINT fk_cancellation_reason FOREIGN KEY(cancellation_reason_id) REFERENCES cancellation_reasons(id)
				,cancellation_reason_location_id varchar(7) NULL
				,CONSTRAINT fk_cancellation_reason_location FOREIGN KEY(cancellation_reason_location_id) REFERENCES locations(id)
				,cancellation_reason_is_near_location boolean NULL

				,diversion_reason_id int NULL
				,CONSTRAINT fk_diversion_reason FOREIGN KEY(diversion_reason_id) REFERENCES cancellation_reasons(id)
				,diversion_reason_location_id varchar(7) NULL
				,CONSTRAINT fk_diversion_reason_location FOREIGN KEY(diversion_reason_location_id) REFERENCES locations(id)
				,diversion_reason_is_near_location boolean NULL

				,diverted_via_location_id varchar(7) NULL
				,CONSTRAINT fk_diverted_via_location FOREIGN KEY(diverted_via_location_id) REFERENCES locations(id)

				-- Journey
				,is_cancelled boolean NOT NULL

				-- Forecast
				,is_reverse_formation boolean NOT NULL

				,late_reason_id int NULL
				,CONSTRAINT fk_late_reason FOREIGN KEY(late_reason_id) REFERENCES late_reasons(id)
				,late_reason_location_id varchar(7) NULL
				,CONSTRAINT fk_late_reason_location FOREIGN KEY(late_reason_location_id) REFERENCES locations(id)
				,late_reason_is_near_location boolean NULL
);

CREATE TABLE IF NOT EXISTS darwin.schedule_locations ( -- Locations that a schedule visits
				schedule_id char(16)
				,CONSTRAINT fk_schedule FOREIGN KEY(schedule_id) REFERENCES schedules(id) ON DELETE CASCADE
				,sequence int
				,PRIMARY KEY (schedule_id, sequence)

				-- Schedule
				,location_id varchar(7) NOT NULL
				,CONSTRAINT fk_location FOREIGN KEY(location_id) REFERENCES locations(id)
				,activities char(2) ARRAY NULL
				,planned_activities char(2) ARRAY NULL
				,is_cancelled boolean NOT NULL
				,formation_id varchar(20) NULL
				,is_affected_by_diversion boolean NOT NULL

				,type text NOT NULL
				-- Times are given here as text so that they can be serached through in their original format. They can be converted to timestamps as needed.
				,public_arrival_time char(5) NULL -- HH:MM
				,public_departure_time char(5) NULL
				,working_arrival_time	varchar(8) NULL -- HH:MM[:SS]
				,working_passing_time varchar(8) NULL
				,working_departure_time varchar(8) NULL
				,routing_delay int NOT NULL -- in minutes
				,false_destination_location_id varchar(7) NULL
				,CONSTRAINT fk_false_destination_location FOREIGN KEY(false_destination_location_id) REFERENCES locations(id)

				,cancellation_reason_id int NULL
				,CONSTRAINT fk_cancellation_reason FOREIGN KEY(cancellation_reason_id) REFERENCES cancellation_reasons(id)
				,cancellation_reason_location_id varchar(7) NULL
				,CONSTRAINT fk_cancellation_reason_location FOREIGN KEY(cancellation_reason_location_id) REFERENCES locations(id)
				,cancellation_reason_is_near_location boolean NULL

				-- Forecast
				,arrival_estimated_time char(5) NULL -- HH:MM
				,arrival_estimated_working_time char(5) NULL
				,arrival_minimum_estimated_time char(5) NULL
				,arrival_estimated_time_is_unknown boolean NULL
				,arrival_is_delayed boolean NULL
				,arrival_actual_time char(5) NULL
				,arrival_actual_time_class text NULL
				,arrival_data_source text NULL
				,arrival_data_source_system char(4) NULL
				
				,passing_estimated_time char(5) NULL -- HH:MM
				,passing_estimated_working_time char(5) NULL
				,passing_minimum_estimated_time char(5) NULL
				,passing_estimated_time_is_unknown boolean NULL
				,passing_is_delayed boolean NULL
				,passing_actual_time char(5) NULL
				,passing_actual_time_class text NULL
				,passing_data_source text NULL
				,passing_data_source_system char(4) NULL

				,departure_estimated_time char(5) NULL -- HH:MM
				,departure_estimated_working_time char(5) NULL
				,departure_minimum_estimated_time char(5) NULL
				,departure_estimated_time_is_unknown boolean NULL
				,departure_is_delayed boolean NULL
				,departure_actual_time char(5) NULL
				,departure_actual_time_class text NULL
				,departure_data_source text NULL
				,departure_data_source_system char(4) NULL

				,late_reason_id int NULL
				,CONSTRAINT fk_late_reason FOREIGN KEY(late_reason_id) REFERENCES late_reasons(id)
				,late_reason_location_id varchar(7) NULL
				,CONSTRAINT fk_late_reason_location FOREIGN KEY(late_reason_location_id) REFERENCES locations(id)
				,late_reason_is_near_location boolean NULL
				
				,disruption_risk text NULL -- "Delay", "Cancellation", or "Other".
				,disruption_risk_reason_id int NULL
				,CONSTRAINT fk_disruption_risk_reason FOREIGN KEY(disruption_risk_reason_id) REFERENCES late_reasons(id)
				,disruption_risk_reason_location_id text NULL
				,CONSTRAINT fk_disruption_risk_reason_location FOREIGN KEY(disruption_risk_reason_location_id) REFERENCES locations(id)
				,disruption_risk_reason_is_near_location boolean NULL

				,affected_by varchar(16) NULL
 				,length int NULL -- may or may not match formation data
				,platform_is_supressed boolean NULL
				,platform_is_supressed_by_cis boolean NULL
				,platform_data_source char NULL -- "P", "A", "M"
				,platform_confirmed boolean NULL
				,platform varchar(3) NULL -- also set by Journey data in timetables
				,is_suppressed boolean NULL
				,detaches_from_front boolean NULL
);

-- associations

CREATE TABLE IF NOT EXISTS darwin.associations ( -- Links between two schedules
				id uuid PRIMARY KEY -- Generated by railreader (not given by Darwin)

				-- sources
				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
				,timetable_id char(14) NULL
				,CONSTRAINT fk_timetable FOREIGN KEY(timetable_id) REFERENCES timetables(id) ON DELETE CASCADE

				-- Association
				,location_id varchar(7) NOT NULL
				,CONSTRAINT fk_location FOREIGN KEY(location_id) REFERENCES locations(id)
				,category char(2) NOT NULL -- "JJ", "VV", "LK", "NP"
				,is_cancelled boolean NOT NULL -- won't happen
				,is_deleted boolean NOT NULL -- doesn't exist
				,main_schedule_id char(16) NOT NULL
				,CONSTRAINT fk_main_schedule FOREIGN KEY(main_schedule_id) REFERENCES schedules(id) ON DELETE CASCADE
				,main_schedule_location_sequence int NOT NULL -- sequence number in the schedule_locations table
				,CONSTRAINT fk_main_schedule_location FOREIGN KEY(main_schedule_id, main_schedule_location_sequence) REFERENCES schedule_locations(schedule_id, sequence) ON DELETE CASCADE
				,associated_schedule_id char(16) NOT NULL
				,CONSTRAINT fk_associated_schedule FOREIGN KEY(associated_schedule_id) REFERENCES schedules(id) ON DELETE CASCADE
				,associated_schedule_location_sequence int NOT NULL -- sequence number in the schedule_locations table
				,CONSTRAINT fk_associated_schedule_location FOREIGN KEY(associated_schedule_id, associated_schedule_location_sequence) REFERENCES schedule_locations(schedule_id, sequence) ON DELETE CASCADE
);

-- alarms

CREATE TABLE IF NOT EXISTS darwin.alarms ( -- Alarms raised when Darwin has not recieved data from some of its sources.
		  	id int PRIMARY KEY -- Unique ID for the alarm.

				-- sources
				,message_id text NULL
				,CONSTRAINT fk_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE

				,received_at timestamp WITH TIME ZONE NOT NULL
				,has_cleared boolean NOT NULL
				,cleared_at timestamp WITH TIME ZONE NULL
				,train_describer_failure char(2) NULL -- a specific train describer that is suspected to have failed
				,all_train_describers_failed boolean NOT NULL
				,tyrell_failed boolean NOT NULL
);
