BEGIN;

-- SCHEDULES

DO $$ BEGIN
	CREATE TYPE disruption_reason AS (
		reason text,
		is_near_tiploc boolean,
		tiploc text
	);
	
	CREATE TYPE uncertainty AS (
		effect text,
		reason disruption_reason
	);
	
	CREATE TYPE service_location_platform AS (
		suppressed boolean,
		suppressed_by_cis boolean,
		source text,
		confirmed boolean,
		platform_number text
	);
	
	CREATE TYPE service_location_forecast AS (
		estimated_time text,
		actual_time text,
		actual_time_source text,
		estimated_time_minimum text,
		estimated_time_unknown boolean,
		delayed boolean,
		source text,
		source_system text
	);
	
	CREATE TYPE service_location AS (
		location_type text,
		tiploc text,
		activities text,
		planned_activities text,
		cancelled boolean,
		formation_id text,
		is_affected_by_diversion boolean,
		late_reason disruption_reason,
		cancellation_reason disruption_reason,
		public_arrival_time text,
		public_departure_time text,
		working_arrival_time text,
		working_departure_time text,
		working_passing_time text,
		routing_delay text,
		false_destination text,
		uncertainty uncertainty,
		affected_by text,
		length integer,
		platform service_location_platform,
		suppressed boolean,
		detaches_from_front boolean,
		arrival_forecast service_location_forecast,
		departure_forecast service_location_forecast,
		passing_forecast service_location_forecast
	);
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS services (
	rid text PRIMARY KEY,
	uid text NOT NULL,
	start_date date NOT NULL,
	headcode text NOT NULL,
	retail_service_id text,
	train_operating_company text NOT NULL,
	service text NOT NULL,
	category text NOT NULL,
	is_passenger_service boolean NOT NULL,
	is_deactivated boolean NOT NULL,
	is_deleted boolean NOT NULL,
	is_charter boolean NOT NULL,
	cancellation_reason disruption_reason,
	diversion_reason disruption_reason,
	diverted_via text,
	is_reverse_formation boolean NOT NULL,
	late_reason disruption_reason,
	locations service_location[] NOT NULL
);

-- ALARMS

CREATE TABLE IF NOT EXISTS alarms (
	alarm_id bigint PRIMARY KEY,
	is_cleared boolean NOT NULL,
	train_describer_failed_area text,
	train_describer_total_feed_failure boolean,
	tyrell_total_feed_failure boolean
);

-- ASSOCIATIONS

DO $$ BEGIN
	CREATE TYPE associated_service AS (
		rid text,
		public_arrival_time text,
		public_departure_time text,
		working_arrival_time text,
		working_departure_time text,
		working_passing_time text
	);
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS associations (
	association_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	tiploc text NOT NULL,
	category text NOT NULL,
	is_cancelled boolean NOT NULL,
	main_service associated_service NOT NULL,
	associated_service associated_service NOT NULL
);

-- FORMATIONS

DO $$ BEGIN
	CREATE TYPE formation_coach AS (
		identifier text,
		class text,
		toilet_status text,
		toilet_type text,
	);
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS formations (
	formation_id text PRIMARY KEY,
	rid text NOT NULL,
	source text,
	source_system text,
	coaches formation_coach[] NOT NULL,
);

COMMIT;
