BEGIN;

DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS schedules_locations CASCADE;

DROP TABLE IF EXISTS alarms CASCADE;
DROP TABLE IF EXISTS timetable_files CASCADE;

DROP TABLE IF EXISTS message_response CASCADE;
DROP TABLE IF EXISTS message_status CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS message_xml CASCADE;

DROP TABLE IF EXISTS loading_categories CASCADE;
DROP TABLE IF EXISTS customer_information_systems CASCADE;
DROP TABLE IF EXISTS via_conditions CASCADE;
DROP TABLE IF EXISTS cancellation_reasons CASCADE;
DROP TABLE IF EXISTS late_reasons CASCADE;
DROP TABLE IF EXISTS train_operating_companies CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS reference_files CASCADE;

DROP TABLE IF EXISTS outbox CASCADE;

COMMIT;
